version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "7988:3000"  # Expose frontend to the host
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}  # Use the environment variable
  backend:
    build: ./backend
    ports:
      - "7989:80"  # Expose the port only to linked services
    volumes:
      - ./data:/app/data