version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "7989:80"
    volumes:
      - ./data:/app/data
  frontend:
    build:
      context: ./frontend
    ports:
      - "7988:3000"
